//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.6.1055.0.
// 
namespace vMixMonitor.Data {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class vmix {
        
        private string versionField;
        
        private string editionField;
        
        private string presetField;
        
        private vmixInput[] inputsField;
        
        private vmixOverlay[] overlaysField;
        
        private uint previewField;
        
        private uint activeField;
        
        private string fadeToBlackField;
        
        private vmixTransition[] transitionsField;
        
        private string recordingField;
        
        private string externalField;
        
        private string streamingField;
        
        private string playListField;
        
        private string multiCorderField;
        
        private string fullscreenField;
        
        private vmixAudio audioField;
        
        /// <remarks/>
        public string version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
            }
        }
        
        /// <remarks/>
        public string edition {
            get {
                return this.editionField;
            }
            set {
                this.editionField = value;
            }
        }
        
        /// <remarks/>
        public string preset {
            get {
                return this.presetField;
            }
            set {
                this.presetField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("input", IsNullable=false)]
        public vmixInput[] inputs {
            get {
                return this.inputsField;
            }
            set {
                this.inputsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("overlay", IsNullable=false)]
        public vmixOverlay[] overlays {
            get {
                return this.overlaysField;
            }
            set {
                this.overlaysField = value;
            }
        }
        
        /// <remarks/>
        public uint preview {
            get {
                return this.previewField;
            }
            set {
                this.previewField = value;
            }
        }
        
        /// <remarks/>
        public uint active {
            get {
                return this.activeField;
            }
            set {
                this.activeField = value;
            }
        }
        
        /// <remarks/>
        public string fadeToBlack {
            get {
                return this.fadeToBlackField;
            }
            set {
                this.fadeToBlackField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("transition", IsNullable=false)]
        public vmixTransition[] transitions {
            get {
                return this.transitionsField;
            }
            set {
                this.transitionsField = value;
            }
        }
        
        /// <remarks/>
        public string recording {
            get {
                return this.recordingField;
            }
            set {
                this.recordingField = value;
            }
        }
        
        /// <remarks/>
        public string external {
            get {
                return this.externalField;
            }
            set {
                this.externalField = value;
            }
        }
        
        /// <remarks/>
        public string streaming {
            get {
                return this.streamingField;
            }
            set {
                this.streamingField = value;
            }
        }
        
        /// <remarks/>
        public string playList {
            get {
                return this.playListField;
            }
            set {
                this.playListField = value;
            }
        }
        
        /// <remarks/>
        public string multiCorder {
            get {
                return this.multiCorderField;
            }
            set {
                this.multiCorderField = value;
            }
        }
        
        /// <remarks/>
        public string fullscreen {
            get {
                return this.fullscreenField;
            }
            set {
                this.fullscreenField = value;
            }
        }
        
        /// <remarks/>
        public vmixAudio audio {
            get {
                return this.audioField;
            }
            set {
                this.audioField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class vmixInput {
        
        private string keyField;
        
        private uint numberField;
        
        private string typeField;
        
        private string titleField;
        
        private string shortTitleField;
        
        private string stateField;
        
        private uint positionField;
        
        private uint durationField;
        
        private string loopField;
        
        private string mutedField;
        
        private decimal volumeField;
        
        private bool volumeFieldSpecified;
        
        private string balanceField;
        
        private string soloField;
        
        private string audiobussesField;
        
        private byte meterF1Field;
        
        private bool meterF1FieldSpecified;
        
        private byte meterF2Field;
        
        private bool meterF2FieldSpecified;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public uint number {
            get {
                return this.numberField;
            }
            set {
                this.numberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string title {
            get {
                return this.titleField;
            }
            set {
                this.titleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string shortTitle {
            get {
                return this.shortTitleField;
            }
            set {
                this.shortTitleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string state {
            get {
                return this.stateField;
            }
            set {
                this.stateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public uint position {
            get {
                return this.positionField;
            }
            set {
                this.positionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public uint duration {
            get {
                return this.durationField;
            }
            set {
                this.durationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string loop {
            get {
                return this.loopField;
            }
            set {
                this.loopField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string muted {
            get {
                return this.mutedField;
            }
            set {
                this.mutedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal volume {
            get {
                return this.volumeField;
            }
            set {
                this.volumeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool volumeSpecified {
            get {
                return this.volumeFieldSpecified;
            }
            set {
                this.volumeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string balance {
            get {
                return this.balanceField;
            }
            set {
                this.balanceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string solo {
            get {
                return this.soloField;
            }
            set {
                this.soloField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string audiobusses {
            get {
                return this.audiobussesField;
            }
            set {
                this.audiobussesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public byte meterF1 {
            get {
                return this.meterF1Field;
            }
            set {
                this.meterF1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool meterF1Specified {
            get {
                return this.meterF1FieldSpecified;
            }
            set {
                this.meterF1FieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public byte meterF2 {
            get {
                return this.meterF2Field;
            }
            set {
                this.meterF2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool meterF2Specified {
            get {
                return this.meterF2FieldSpecified;
            }
            set {
                this.meterF2FieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class vmixOverlay {
        
        private uint numberField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public uint number {
            get {
                return this.numberField;
            }
            set {
                this.numberField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class vmixTransition {
        
        private byte numberField;
        
        private string effectField;
        
        private ushort durationField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public byte number {
            get {
                return this.numberField;
            }
            set {
                this.numberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string effect {
            get {
                return this.effectField;
            }
            set {
                this.effectField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public ushort duration {
            get {
                return this.durationField;
            }
            set {
                this.durationField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class vmixAudio {
        
        private vmixAudioMaster masterField;
        
        /// <remarks/>
        public vmixAudioMaster master {
            get {
                return this.masterField;
            }
            set {
                this.masterField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class vmixAudioMaster {
        
        private byte volumeField;
        
        private string mutedField;
        
        private byte meterF1Field;
        
        private byte meterF2Field;
        
        private byte headphonesVolumeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public byte volume {
            get {
                return this.volumeField;
            }
            set {
                this.volumeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string muted {
            get {
                return this.mutedField;
            }
            set {
                this.mutedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public byte meterF1 {
            get {
                return this.meterF1Field;
            }
            set {
                this.meterF1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public byte meterF2 {
            get {
                return this.meterF2Field;
            }
            set {
                this.meterF2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public byte headphonesVolume {
            get {
                return this.headphonesVolumeField;
            }
            set {
                this.headphonesVolumeField = value;
            }
        }
    }
}
